USE COMERCIO_OLTP
GO

SELECT COUNT(*) FROM CLIENTE
GO

SELECT COUNT(*) FROM ENDERECO
GO

SELECT * FROM CLIENTE
GO

SELECT * FROM ENDERECO
GO

SELECT C.NOME, E.RUA
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
GO

SELECT COUNT(*) AS QUANTIDADE
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
GO